### ISSUE TITLE
Query not working

### ISSUE THREAD

**Issue by marcelo-ventura** [rakeshgunduka/gaapi#4]
Hello there, thanks for your package development.

When I run this command 

```
ga.batch_get(query_py)
```

it returns me the following error:

```
File "/home/04300609128/anaconda3/lib/python3.7/site-packages/gaapi/__init__.py", line 87, in batch_get
   if isinstance(obj, Query):

NameError: name 'obj' is not defined

```

I've followed the same steps in https://github.com/rakeshgunduka/gaapi
Thanks a lot for your attention. Regards, Marcelo

**Comment by rolence0515** [comment]
me too

**Comment by rakeshgunduka** [comment]
@marcelo-ventura  @rolence0515 Thanks for raising this. I have been offline for a while.
I have fixed it. Cheers.
